config/routes.rb
Rails.application.routes.draw do

  devise_for :adms
  devise_for :users
  resources :users
  resources :atendimentos
  resources :adms
root to: 'pages#index'

end

app/models/adm.rb
class Adm < ActiveRecord::Base
	has_many :atendimentos
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/atendimento.rb
class Atendimento < ActiveRecord::Base
	belongs_to :user
	belongs_to :adm

	def completed?
		!completed_at.blank?
	end
end

app/models/user.rb
class User < ActiveRecord::Base
 has_many :atendimentos
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/adms_controller.rb
class AdmsController < ApplicationController
  before_action :set_adm, only: [:show, :edit, :update, :destroy]

  # GET /adms
  # GET /adms.json
  def index
    @adms = Adm.all
  end

  # GET /adms/1
  # GET /adms/1.json
  def show
  end

  # GET /adms/new
  def new
    @adm = Adm.new
  end

  # GET /adms/1/edit
  def edit
  end

  # POST /adms
  # POST /adms.json
  def create
    @adm = Adm.new(adm_params)

    respond_to do |format|
      if @adm.save
        format.html { redirect_to @adm, notice: 'Administrador criado com sucesso!.' }
        format.json { render :show, status: :created, location: @adm }
      else
        format.html { render :new }
        format.json { render json: @adm.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adms/1
  # PATCH/PUT /adms/1.json
  def update
    respond_to do |format|
      if @adm.update(adm_params)
        format.html { redirect_to @adm, notice: 'Administrador was successfully updated.' }
        format.json { render :show, status: :ok, location: @adm }
      else
        format.html { render :edit }
        format.json { render json: @adm.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adms/1
  # DELETE /adms/1.json
  def destroy
    @adm.destroy
    respond_to do |format|
      format.html { redirect_to adms_url, notice: 'Administrador was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adm
      @adm = Adm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adm_params
      params.require(:adm).permit(:nome, :senha, :registro)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/atendimentos_controller.rb
class AtendimentosController < ApplicationController
  before_action :set_atendimento, only: [:show, :edit, :update, :destroy]

  # GET /atendimentos
  # GET /atendimentos.json
  def index
        if user_signed_in?
    @atendimentos = current_user.atendimentos(:user_id => current_user.id).order("created_at DESC")
      end
       if adm_signed_in?
    @atendimentos = current_adm.atendimentos(:adm_id => current_adm.id).order("created_at DESC")
      end
  end


  # GET /atendimentos/1
  # GET /atendimentos/1.json
  def show

  end

  # GET /atendimentos/new
  def new
    if user_signed_in?
   @atendimento = current_user.atendimentos.build
    end
    if adm_signed_in?
   @atendimento = current_adm.atendimentos.build
    end
  end

  # GET /atendimentos/1/edit
  def edit
  end

  # POST /atendimentos
  # POST /atendimentos.json
  def create
    if user_signed_in?
    @atendimento = current_user.atendimentos.build(atendimento_params)
    end

    if adm_signed_in?
    @atendimento = current_adm.atendimentos.build(atendimento_params)
    end

    respond_to do |format|
      if @atendimento.save
        format.html { redirect_to @atendimento, notice: 'Atendimento was successfully created.' }
        format.json { render :show, status: :created, location: @atendimento }
      else
        format.html { render :new }
        format.json { render json: @atendimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /atendimentos/1
  # PATCH/PUT /atendimentos/1.json
  def update
    respond_to do |format|
      if @atendimento.update(atendimento_params)
        format.html { redirect_to @atendimento, notice: 'Atendimento was successfully updated.' }
        format.json { render :show, status: :ok, location: @atendimento }
      else
        format.html { render :edit }
        format.json { render json: @atendimento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /atendimentos/1
  # DELETE /atendimentos/1.json
  def destroy
    @atendimento.destroy
    respond_to do |format|
      format.html { redirect_to atendimentos_url, notice: 'Atendimento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_atendimento
      @atendimento = Atendimento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def atendimento_params
      params.require(:atendimento).permit(:categoria, :area, :data, :detalhes)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def index
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:nome, :senha, :registro)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/atendimentos_helper.rb
module AtendimentosHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/adms/_form.html.erb
<%= form_for @adm, :html => { :class => "form-horizontal adm" } do |f| %>

  <% if @adm.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@adm.errors.count, "error") %> prohibited this adm from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nome) %>
  </div>
  <div class="form-group">
    <%= f.label :senha, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :senha, :class => 'form-control' %>
    </div>
    <%=f.error_span(:senha) %>
  </div>
  <div class="form-group">
    <%= f.label :registro, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :registro, :class => 'form-control' %>
    </div>
    <%=f.error_span(:registro) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                adms_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/adms/edit.html.erb
<%- model_class = Adm -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/adms/index.html.erb
<%- model_class = Adm-%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:senha) %></th>
      <th><%= model_class.human_attribute_name(:registro) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |adm| %>
      <tr>
        <td><%= link_to adm.id, adm_path(adm) %></td>
        <td><%= adm.nome %></td>
        <td><%= adm.senha %></td>
        <td><%= adm.registro %></td>
        <td><%=l adm.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_adm_path(adm), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      adm_path(adm),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_adm_path,
            :class => 'btn btn-primary' %>

app/views/adms/new.html.erb
<%- model_class = Adm -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/adms/show.html.erb
<%- model_class = Adm -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @adm.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:senha) %>:</strong></dt>
  <dd><%= @adm.senha %></dd>
  <dt><strong><%= model_class.human_attribute_name(:registro) %>:</strong></dt>
  <dd><%= @adm.registro %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              adms_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_adm_path(@adm), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              adm_path(@adm),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/atendimentos/_form.html.erb
<%= form_for @atendimento, :html => { :class => "form-horizontal atendimento" } do |f| %>

  <% if @atendimento.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@atendimento.errors.count, "error") %> prohibited this atendimento from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @atendimento.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :categoria, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :categoria, :class => 'form-control' %>
    </div>
    <%=f.error_span(:categoria) %>
  </div>
  <div class="form-group">
    <%= f.label :area, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :area, :class => 'form-control' %>
    </div>
    <%=f.error_span(:area) %>
  </div>
  <div class="form-group">
    <%= f.label :data, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :data, :class => 'form-control' %>
    </div>
    <%=f.error_span(:data) %>
  </div>
  <div class="form-group">
    <%= f.label :detalhes, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :detalhes, :class => 'form-control' %>
    </div>
    <%=f.error_span(:detalhes) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                atendimentos_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/atendimentos/edit.html.erb
<%- model_class = Atendimento -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/atendimentos/index.html.erb
<%- model_class = Atendimento -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:categoria) %></th>
      <th><%= model_class.human_attribute_name(:area) %></th>
      <th><%= model_class.human_attribute_name(:data) %></th>
      <th><%= model_class.human_attribute_name(:detalhes) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @atendimentos.each do |atendimento| %>
      <tr>
        <td><%= link_to atendimento.id, atendimento_path(atendimento) %></td>
        <td><%= atendimento.categoria %></td>
        <td><%= atendimento.area %></td>
        <td><%= atendimento.data %></td>
        <td><%= atendimento.detalhes %></td>
        <td><%=l atendimento.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_atendimento_path(atendimento), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      atendimento_path(atendimento),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_atendimento_path,
            :class => 'btn btn-primary' %>

app/views/atendimentos/new.html.erb
<%- model_class = Atendimento -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/atendimentos/show.html.erb
<%- model_class = Atendimento -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:categoria) %>:</strong></dt>
  <dd><%= @atendimento.categoria %></dd>
  <dt><strong><%= model_class.human_attribute_name(:area) %>:</strong></dt>
  <dd><%= @atendimento.area %></dd>
  <dt><strong><%= model_class.human_attribute_name(:data) %>:</strong></dt>
  <dd><%= @atendimento.data %></dd>
  <dt><strong><%= model_class.human_attribute_name(:detalhes) %>:</strong></dt>
  <dd><%= @atendimento.detalhes %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              atendimentos_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_atendimento_path(@atendimento), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              atendimento_path(@atendimento),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Sparta300" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to "Sparta300", root_path, class:"navbar-brand"  %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
          
          <% if current_user.present? %>
            <li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Entrar", new_user_session_path %></li>
          <% end %> 
            <!--<li><%= link_to "Sair", destroy_user_session_path  %></li>
            <li><%= link_to "Cadastre-se", new_user_registration_path %></li> -->
          <% if user_signed_in? %>           
            <li><%= link_to "Atendimentos", new_atendimento_path  %></li>
          <%end%>
          <% if adm_signed_in? %>           
            <li><%= link_to "Atendimentos", new_atendimento_path  %></li>
            <li><%= link_to "Cadastrar Usuário", new_user_registration_path %></li>
          <%end%>
          <% if current_adm.present? %>
            <li><%= link_to "Sair", destroy_adm_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Entrar", new_adm_session_path %></li>
          <% end %> 
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <!--<div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
           <!-- <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>-->
           <!--</div><!--/.well -->
        </div><!--/span-->
       </div><!--/row-->

      <footer>
        <!--<p>&copy; Company 2016</p>-->
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/index.html.erb
<div class="jumbotron">
  <h1>Bem vindo ao Sparta300!</h1>
  <p>Agilizando os processos da sua empresa e facilitando a sua vida!</p>


</div>

app/views/users/_form.html.erb
<%= form_for @user, :html => { :class => "form-horizontal user" } do |f| %>

  <% if @user.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nome, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nome) %>
  </div>
  <div class="form-group">
    <%= f.label :senha, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :senha, :class => 'form-control' %>
    </div>
    <%=f.error_span(:senha) %>
  </div>
  <div class="form-group">
    <%= f.label :registro, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :registro, :class => 'form-control' %>
    </div>
    <%=f.error_span(:registro) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                users_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/index.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:senha) %></th>
      <th><%= model_class.human_attribute_name(:registro) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to user.id, user_path(user) %></td>
        <td><%= user.nome %></td>
        <td><%= user.senha %></td>
        <td><%= user.registro %></td>
        <td><%=l user.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_user_path(user), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      user_path(user),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_user_path,
            :class => 'btn btn-primary' %>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @user.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:senha) %>:</strong></dt>
  <dd><%= @user.senha %></dd>
  <dt><strong><%= model_class.human_attribute_name(:registro) %>:</strong></dt>
  <dd><%= @user.registro %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              users_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              user_path(@user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>